### ISSUE TITLE
Resizing the window jumbles the view

### ISSUE THREAD

**Issue by atye** [atye/ttchat#11]
The incoming message stream still works so you can resize the height of the window to match the stream.

**Comment by atye** [comment]
@whanake-music 

Branch https://github.com/atye/ttchat/tree/issue-11 has the beginning of changes for window resizing. You can build from this branch.

One thing I am still working on is condensing messages that span multiple lines to a fewer number of lines when the width is bigger. Let me know how it works for you.

**Comment by atye** [comment]
@whanake-music

Tooke me a bit. I've pushed changes to branch https://github.com/atye/ttchat/tree/issue-11 that support window resizing. Can you build this branch and see if it works for you?

**Comment by atye** [comment]
@whanake-music

This should be resolved in the latest release. I'm going to close this.

**Comment by whanake-music** [comment]
I'll give it a shot as soon as I can. Apologies for the inactivity, it's been a busy year
