### ISSUE TITLE
Add access token to configuration file

### ISSUE THREAD

**Issue by KaMyKaSii** [atye/ttchat#18]
Instead of opening the authorization link every time when running the program, could you add the access token to the configuration file? I would also like to use the program on a machine without a desktop environment and this is making it impossible. Thank you!

**Comment by atye** [comment]
@KaMyKaSii 

You can pass in your own access token with the `--token` flag:

```
ttchat --channel <channel> --token randomAccessToken
```

The documentation in the latest release is updated to show this.

**Comment by KaMyKaSii** [comment]
> @KaMyKaSii
> 
> You can pass in your own access token with the `--token` flag:
> 
> ```
> ttchat --channel <channel> --token randomAccessToken
> ```
> 
> The documentation in the latest release is updated to show this. Make sure the token has the scopes to read and edit/write chat.

Working, thank you! Also I would like to know, is it possible to start/put ttchat in backgroung in the shell? I tried with & at the end of the command but the process is killed right away, CTRL Z during execution does nothing

**Comment by atye** [comment]
@KaMyKaSii 

Hm, no I don't think that is possible right now. Why would you want to put it in the background?
