### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by whanake-music** [atye/ttchat#24]
There is currently no way to change the line spacing. It would be nice to add a parameter in `config.yaml` that lets you change the spacing between lines for a more compact/spaced view.

**Comment by atye** [comment]
Do you have Go installed in your environment? I have changes on branch https://github.com/atye/ttchat/tree/issue-24 that should resolve both of your issues (line spacing and wrapping) but before I publish a release, it would be great if you could verify that it works for you.

If you have Go you can clone the repository, checkout the issue-24 branch, and run `make build` if you're on a *nix machine. You can also run the go build command in the Makefile manually.

Or, I can build the binary and attach it here. I just need to know what your OS is.

**Comment by whanake-music** [comment]
I've been using the latest binary on the Releases page, don't think I have Go installed, no. If you could build the binary for me, that would be awesome! My OS is Manjaro Linux

**Comment by whanake-music** [comment]
Update: Just installed Go and built from issue-24. `lineSpacing` config option works great and the spacing for the chat itself has been fixed. Line wrapping is OK, but it doesn't update if the terminal window is resized after launch. And the chat input prompt has extra line spacing above and below it; although that may be intentional. :)

**Comment by atye** [comment]
I haven't implemented window resizing yet but I'll open an issue for it. I intentionally put an extra line above the input prompt but there shouldn't be a a line below the input prompt. Can you send a picture/screenshot of the extra line below it? I don't see it in my testing.

**Comment by whanake-music** [comment]
I don't know quite how to re-create it but I believe it's another issue caused by window resizing. I encounter it when I zoom in or out of my terminal in full-screen mode, which I do fairly regularly. I'll post a screenshot next time I see it

**Comment by atye** [comment]
Ok, when window resizing is better supported hopefully that will be fixed. I'll merge the line wrapping and line spacing changes to main but I'll see if I can include window resizing in another PR before I publish a new release.

**Comment by atye** [comment]
The main branch has the changes for the line spacing and line wrapping. I didn't make any further changes since you built the binary yourself so what you have should be fine but you can build from main if you want.

I'm going to close this and the line wrapping issue. We'll continue with https://github.com/atye/ttchat/issues/11.
