### ISSUE TITLE
not working with access token

### ISSUE THREAD

**Issue by MadDaimond** [atye/ttchat#28]
OS: AntiX 19 (based on Debian 10), terminal: Roxterm.
First of all, thanks for this awesome program. I am trying to setup ttchat with my own access token for not open the browser every time, but have no success. What I did:
1) I am already get my own "app access token" as written at Twitch FAQ.
2) When I do in terminal:

ttchat -c "channel name" --token "app access token"

the program opens, the "send the message" line appears, but nothing more happens. The program is not receives or sends messages.
What I am doing wrong?

**Comment by atye** [comment]
Hello, I am not sure what is wrong but we can try some things.

Can you try it without quotes like `ttchat --channel channelName --token accessToken`?
Are you sure that your access token has the permissions/privileges to read and edit chat?
Does it not work for every channel or only specific channels? 
Does it work when you don't provide your own token and use the browser?
Have you tried on another OS?

I don't have a Debian environment but I will see if I can get one and test some things.

**Comment by MadDaimond** [comment]
Oh, I am not using a quotes in actual command.

I am tried to get access token first time in my live, so, the problem can be with it. I am doing it with "curl" and my command was looked like this:

curl -X POST 'https://id.twitch.tv/oauth2/token' -H 'Content-Type: application/x-www-form-urlencoded' -d 'client_id=my_client_ID&client_secret=my_client_secret&grant_type=client_credentials

I  am doing it with this section of Twitch FAQ: https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#client-credentials-grant-flow

**Comment by atye** [comment]
Try adding the `chat:read` and `chat:edit` scopes to the token.

https://dev.twitch.tv/docs/authentication/scopes#chat-and-pubsub-scopes

**Comment by MadDaimond** [comment]
Wait. According to this page scopes is not used by "app access token", and I have a "app access token". Do I have a wrong type of token and need the "user access token"?

**Comment by atye** [comment]
Yes, you'll need a user access token with the scopes to read and edit chat. `ttchat` uses the [OIDC Implicit Flow](https://dev.twitch.tv/docs/authentication/getting-tokens-oidc#oidc-implicit-grant-flow). 

You can use https://github.com/twitchdev/twitch-cli/blob/main/docs/token.md to help you generate an appropriate token.

**Comment by atye** [comment]
Actually, it looks like that uses the browser too. If I find something in the docs that generates an appropriate token without the browser, I will post it.

**Comment by MadDaimond** [comment]
Hm, looks I am misunderstood how the ttchat with token works, if it need the browser to work anyway. Can you explain, please, what a point to use the own user token?

**Comment by atye** [comment]
The OAuth flows for Twitch require manual user authorization at some point according to the docs. However, you can save that access token from the browser and use it in the future. The docs don't say anything about an expiration date. 

I tested this by passing the `access_token` value in the browser, which as the appropriate scopes, as the token flag to `ttchat` and it worked. So as long as the token is valid with the `chat:read` and `chat:edit` scopes, it will work. How you get that token is up to you.

**Comment by atye** [comment]
You may also reach out to the user who opened https://github.com/atye/ttchat/issues/18 who appears to be doing what you want.

**Comment by MadDaimond** [comment]
Thank you! I will try to use it and see, what the expiration date of this random tokens on practice. Hope it is longer, than 1 day or so.

**Comment by atye** [comment]
I assume the token is working for you. Feel free to reopen if there are ongoing issues related to this.
